on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: windows-2019
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5

        - name: Navigate to Workspace
          run: cd $GITHUB_WORKSPACE

        - name: Get version
          id: versionReader
          run: |
            $content = $(Get-Content Version.txt)
            echo "VERSION=$content" >> $GITHUB_ENV
            echo "VERSION=$content"

        - name: Restore Packages
          run: nuget restore LuteBot.sln

        - name: Build Solution
          run: |
            msbuild.exe LuteBot.sln /p:platform="Any CPU" /p:configuration="Release"

        - name: Zip Solution
          uses: thedoctor0/zip-release@main
          with:
            directory: LuteBot/bin/Release
            type: zip
            filename: ./LuteBot${{ env.VERSION }}.zip
            exclusions: '*.pdb /app.publish/* *.application'

        - name: Create github Release
          id: create_release
          uses: actions/create-release@v1
          env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
              tag_name: v${{ env.VERSION }}
              release_name: LuteBot v${{ env.VERSION }}
              draft: true
              prerelease: false
        - name: Upload release
          uses: actions/upload-release-asset@v1.0.1
          env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./LuteBot${{ env.VERSION }}.zip
              asset_name: LuteBot${{ env.VERSION }}.zip
              asset_content_type: application/zip
        - name: Publish release
          uses: eregon/publish-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release_id: ${{ steps.create_release.outputs.id }}
